secrets scan

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -22,17 +22,28 @@ jobs:
 
       - uses: ./.github/actions/setup-env
 
-      - name: Run Gitleaks and save report
+      - name: Install Gitleaks
         run: |
-          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
+          wget -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz
+          tar -xvzf gitleaks.tar.gz
           chmod +x gitleaks
-          ./gitleaks detect --source . --report-format json --report-path gitleaks-report.json --exit-code 1
+          sudo mv gitleaks /usr/local/bin/
 
-      - name: Upload Gitleaks report as artifact
+      - name: Run Gitleaks scan
+        run: |
+          gitleaks detect \
+            --source . \
+            --report-format json \
+            --report-path gitleaks-report.json \
+            --exit-code 1 || echo "Gitleaks scan found issues or failed"
+
+      - name: Upload Gitleaks Report
         uses: actions/upload-artifact@v4
         with:
           name: gitleaks-report
           path: gitleaks-report.json
+
+
 
       - uses: ./.github/actions/dependency-scan
         with:
